- name: variables
  hosts: localhost
  vars:
    name: "jahnavi naidana"
    role: "devops engineer"
    time: "2 years"
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "Hi this {{name}} and I'm a {{role}} from last {{time}}."