- name: variables
  hosts: localhost
  vars: #variable declaration
    myself: "jahnavi naidana"
    role: "devops engineer"
    time: "2 years"
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "Hi this {{myself}} and I'm a {{role}} from last {{time}}."